sulu_article.article:
    type: rest
    resource: Sulu\Bundle\ArticleBundle\Controller\ArticleController

sulu_article.article.versioning:
    type: rest
    parent: sulu_article.article
    resource: Sulu\Bundle\ArticleBundle\Controller\VersionController
